"""
Django settings for levi project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""




import os
from pathlib import Path
from decouple import config
from datetime import timedelta
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-ziob($b1bpljb_q=3_+&n@tfc)r-f8px5e2ryrrrw#8$473nfv'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

# Allowed hosts for production (⚠️ Warning: Only use "*" for development, never in production.)
ALLOWED_HOSTS = []

# Allowed hosts for production (production)
'''ALLOWED_HOSTS = [
    'your-actual-domain.com',
    'www.your-actual-domain.com',
    'your-server-ip-address',
]'''



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    #add stuffs here
    'levi.myapp',  # Our Custom App
    'rest_framework',  # For building APIs
    'rest_framework.authtoken',  # For token authentication
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'levi.levi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'levi.wsgi.application'



# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''


#Replace the SQLite DATABASES configuration with PostgreSQL
DATABASES = {
    'default': dj_database_url.config(
        # Replace this value with your local database's connection string.
        default=os.environ.get(
            key="postgresql://go_levi_progresdb_user:PU64fUGSydhMAG0uFUU9vrcoPARAnKZg@dpg-d32t7pfdiees7393et30-a.oregon-postgres.render.com/go_levi_progresdb", 
            default="sqlite:///db.sqlite3"
        ),
        conn_max_age=600
    )
}




# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
#
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (user uploaded files) ################
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Custom user model
AUTH_USER_MODEL = 'myapp.User'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        #'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



#DRF SIMPLE JWT SETTINGS
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),   # 24 hours expiry
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),    # refresh valid for 1 day
    "ROTATE_REFRESH_TOKENS": False,                  # optional: issue new refresh on use
    "BLACKLIST_AFTER_ROTATION": True,               # optional: blacklist old refresh
    "AUTH_HEADER_TYPES": ("Bearer",),
}



# Email settings (for password reset and notifications)
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For Development Prints emails to console
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # For Production Prints emails to console
# OR (for real emails)

EMAIL_BACKEND = config('EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST') # Your SMTP server
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD') #Generate your 16 digits password later
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')


AUTHENTICATION_BACKENDS = [
    'myapp.backends.EmailBackend',  # Replace 'myapp' with your app name # Your custom backend
    #'django.contrib.auth.backends.ModelBackend',  # Fallback to default
]


# Used config from python "decouple" to pull out values from the .env file
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)
PAYSTACK_TEST_SECRET_KEY = config("PAYSTACK_SECRET_KEY")

# CELERY BROKER URL FOR REDIS (TO RUN CRON JOBS)
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"   # Redis DB 0
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

